### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/nextcloud-axios#151]
```js
import axios from '@nextcloud/axios'

axios.post('/some/url')
```
```
       Asset      Size  Chunks             Chunk Names
ajax-size.js  51.2 KiB       0  [emitted]  ajax-size
```
vs
```js
import axios from 'axios'

axios.post('/some/url', null, {headers: {requesttoken: OC.requestToken}})
```
```
       Asset      Size  Chunks             Chunk Names
ajax-size.js  15.7 KiB       0  [emitted]  ajax-size
```
35kb minified js code just for setting header... are you serious ?

BTW `jQuery.post('/some/url')` - size `24 bytes` :smile:

**Comment by ChristophWurst** [comment]
> 35kb minified js code just for setting header... are you serious ?

No, I put this library out as a trap. My intention is to increase everyone's bundles and make their code slow.

> BTW `jQuery.post('/some/url')` - size `24 bytes` smile

:apple: and :orange_circle:. You're comparing a bundle with a function call. Very fair. If you're referring to the global `$` in Nextcloud then sorry to disappoint but this is deprecated and will be removed as written on so many places.

**Comment by ChristophWurst** [comment]
Feel free to drop constructive feedback here. Spin up a bundle analyzer and inspect why our abstraction is so much bigger than the original lib.

**Comment by zorn-v** [comment]
> My intention is to increase everyone's bundles and make their code slow.

:smiley: 

>  but this is deprecated and will be removed as written on so many places

Yes I know

> Feel free to drop constructive feedback here

Well, I think it is because `onRequestTokenUpdate` wich in fact something like bloated alternative of `addEventListener/dispatchEvent`

**Comment by zorn-v** [comment]
Hmm, the biggest squares is for `semver` in analyzer. Is it really needed for event-bus ?

**Comment by ChristophWurst** [comment]
> `semver` in analyzer. Is it really needed for event-bus ?

Is this a trick question again? Of course it's needed, otherwise we'd remove it :speak_no_evil:

**Comment by zorn-v** [comment]
I mean REALLY ) 
Do you agree that 35kb is too much for simple thing that this package do ?
All usage of semver package is here
https://github.com/nextcloud/nextcloud-event-bus/blob/e2ff4f2258c1abcfb9d5fbfb281d1af2fecabdd5/lib/ProxyBus.ts#L13-L20
just for 2 warnings...

**Comment by ChristophWurst** [comment]
So what would you suggest? Remove the check, hope for the best and have someone debug if it :hankey: hits the fan?

**Comment by zorn-v** [comment]
Use regexp for example. Or simple split by "." of version string. 
Need to check benefits for total size after removing semver dep.

**Comment by zorn-v** [comment]
Or maybe use another, less size package like https://www.npmjs.com/package/compare-versions

**Comment by zorn-v** [comment]
> Need to check benefits for total size after removing semver dep.

Difference about 7.3Kb

**Comment by ChristophWurst** [comment]
We should update the event bus here and re-evaluate because of https://github.com/nextcloud/nextcloud-event-bus/pull/107. The new bundle size might be a lot smaller.

**Comment by ChristophWurst** [comment]
Let me tag a release so we have https://github.com/nextcloud/nextcloud-axios/pull/137/commits/3ba2249808bd10fde18ab2200ac235ab643fc510 published

**Comment by ChristophWurst** [comment]
That didn't help much according to https://bundlephobia.com/result?p=@nextcloud/axios@1.3.3. But that also shows that core-js takes the much bigger share of bundle size, the event bus is minor compared to that.

**Comment by zorn-v** [comment]
> But that also shows that core-js takes the much bigger share of bundle size

Is not typescript can compile to specified target (ES5 for example) ? 
I mean what a sense of `core-js` polyfills then ?

**Comment by ChristophWurst** [comment]
Yes, but just es5. So the apps that use this lib would have to transpile the code again. We use babel and https://www.npmjs.com/package/@nextcloud/browserslist-config instead and pit out something that is already processable by the supported browsers (minus linking the chunks to one bundle).

**Comment by zorn-v** [comment]
> Yes, but just es5... We use babel and https://www.npmjs.com/package/@nextcloud/browserslist-config...

Well, let's compare.
```
# browserslist-config
  'last 2 versions',
  'ie >= 11',
  'firefox ESR',
  'not dead'
```
https://caniuse.com/#search=es5
'last 2 versions' - true (even IE)
'ie >= 11' - true (see prev)
'firefox ESR' - true (ESR is 78 now)
`not dead` - true (no comments)

**Comment by ChristophWurst** [comment]
Awesome. But in that case I'm wondering why core-js is still inserted in so many place. Shouldn't it just have 0 `require`s and not be used if the claim is true?

**Comment by zorn-v** [comment]
Maybe it is just habit caused by harsh past of javascript :smile:

**Comment by vinicius73** [comment]
The `@nextcloud/axios` v2 is ~60% smaller than v2

https://bundlephobia.com/package/@nextcloud/axios@2.0.0
