### ISSUE TITLE
"error.request is undefined" when a request is cancelled

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/nextcloud-axios#548]
Regression introduced in #510

`config`, `response` and `request` may not be defined in some cases, so since #510 trying to [destructure `request: { responseURL }`](https://github.com/nextcloud/nextcloud-axios/blob/94559f638fc21fe1fbe8dc322aa64ad28e925f4e/lib/interceptors/maintenance-mode.ts#L4) fails in those cases (`error.request is undefined`). This can be seen when [a request is canceled in Talk](https://github.com/nextcloud/spreed/issues/8159), although I do not know if the problem is specific to [using](https://github.com/nextcloud/spreed/blob/47e98d86d617925253f69f4a5a7ad67d63fd4d79/src/utils/cancelableRequest.js#L39) the [deprecated `CancelToken`](https://axios-http.com/docs/cancellation) or if it happens too when a request is aborted using the `AbortController` (or in other cases).

**Comment by julien-nc** [comment]
The problem is the same whether we use `AbortController` or `CancelToken`. The suggested fix solves the issue in both cases.

**Comment by ChristophWurst** [comment]
2.3.0 released.
