### ISSUE TITLE
Release 2.4

### ISSUE THREAD

**Issue by susnux** [nextcloud/nextcloud-axios#627]
@ChristophWurst do you think we can prepare a 2.4 release (or a new 2.4 RC)?
I would appreciate to have the latest fixes released :)

**Comment by ChristophWurst** [comment]
sure

**Comment by skjnldsv** [comment]
The 2.4 release breaks cypress in many repos for some reason.
https://github.com/nextcloud/viewer/actions/runs/5989883555/job/16246600700
https://github.com/nextcloud/photos/actions/runs/5798646767/job/15717925031
